name: l2flutter
description: A Flutter project for cross-platform mobile development.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI相关
  cupertino_icons: ^1.0.2
  
  # 状态管理
  provider: ^6.1.1
  
  # 网络请求
  http: ^1.1.0
  dio: ^5.3.2
  
  # 本地存储
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # 路由管理
  go_router: ^12.1.1
  
  # 工具类
  intl: ^0.18.1
  logger: ^2.0.2+1
  
  # 图片处理
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # 权限处理
  permission_handler: ^11.0.1
  
  # 设备信息
  device_info_plus: ^9.1.1
  
  # 网络状态
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  
  # 代码分析
  flutter_lints: ^3.0.0
  
  # 测试相关
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # 资源文件配置
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # 字体配置
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 