name: Flutter CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_build: web
            build_target: release
            build_path: build/web
            artifact_name: web-build
          - os: windows-latest
            flutter_build: windows
            build_target: release
            build_path: build/windows/runner/Release
            artifact_name: windows-build
          - os: macos-latest
            flutter_build: macos
            build_target: release
            build_path: build/macos/Build/Products/Release
            artifact_name: macos-build

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          architecture: x64
          cache: true
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Enable platforms
        run: |
          if [ "${{ matrix.flutter_build }}" = "windows" ]; then
            flutter config --enable-windows-desktop
          elif [ "${{ matrix.flutter_build }}" = "macos" ]; then
            flutter config --enable-macos-desktop
          fi
        shell: bash
        
      - name: Build ${{ matrix.flutter_build }}
        run: |
          if [ "${{ matrix.flutter_build }}" = "web" ]; then
            flutter build web --release
          elif [ "${{ matrix.flutter_build }}" = "windows" ]; then
            flutter build windows --release
          elif [ "${{ matrix.flutter_build }}" = "macos" ]; then
            flutter build macos --release
          fi
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.build_path }}

  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          architecture: x64
          cache: true
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk
          
  create-release:
    needs: [build-and-release, build-android]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: true
          files: |
            windows-build/**
            web-build/**
            macos-build/**
            android-build/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 